<?php
/** @package Movitory::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("MovieMap.php");

/**
 * MovieDAO provides object-oriented access to the movies table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Movitory::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class MovieDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Name;

	/** @var int */
	public $Year;

	/** @var string */
	public $Location;

	/** @var string */
	public $Barcode;

	/** @var string */
	public $Rating;

	/** @var int */
	public $Contactid;

	/** @var int */
	public $Extraid;


	/**
	 * Returns a dataset of Moviesactors objects with matching Movieid
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetMovieidMoviesactorss($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "moviesActors_ibfk_1", $criteria);
	}

	/**
	 * Returns a dataset of Moviesgenres objects with matching Movieid
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetMovieidMoviesgenress($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "moviesGenres_ibfk_1", $criteria);
	}

	/**
	 * Returns a dataset of Moviesgroups objects with matching Movieid
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetMovieidMoviesgroupss($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "moviesGroups_ibfk_1", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of Contactid
	 * @return Contacts
	 */
	public function GetContactidContacts()
	{
		return $this->_phreezer->GetManyToOne($this, "movies_ibfk_1");
	}

	/**
	 * Returns the foreign object based on the value of Extraid
	 * @return Extras
	 */
	public function GetExtraidExtras()
	{
		return $this->_phreezer->GetManyToOne($this, "movies_ibfk_2");
	}


}
?>