<?php
/** @package Movitory::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("Movie_GroupMap.php");

/**
 * Movie_GroupDAO provides object-oriented access to the moviesGroups table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Movitory::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class Movie_GroupDAO extends Phreezable
{
	/** @var int */
	public $Movieid;

	/** @var int */
	public $Groupid;


	/**
	 * Returns the foreign object based on the value of Movieid
	 * @return Movies
	 */
	public function GetMovieidMovies()
	{
		return $this->_phreezer->GetManyToOne($this, "moviesGroups_ibfk_1");
	}

	/**
	 * Returns the foreign object based on the value of Groupid
	 * @return Groups
	 */
	public function GetGroupidGroups()
	{
		return $this->_phreezer->GetManyToOne($this, "moviesGroups_ibfk_2");
	}


}
?>