<?php
	$this->assign('title','MOVITORY | Home');
	$this->assign('nav','home');

	$this->display('_Header.tpl.php');
?>

	<div class="modal hide fade" id="getStartedDialog">
		<div class="modal-header">
			<a class="close" data-dismiss="modal">&times;</a>
			<h3>Getting Started With Phreeze</h3>
		</div>
		<div class="modal-body" style="max-height: 300px">
			<p>This site has been generated by Phreeze classbuilder and contains basic DB
			read and write capability.  One UI page has been created for each table in your
			database.  Click on the links in the top navigation bar to view the pages.</p>

			<p>The application is not intended to use as-is unless you only want
			a simple web interface to your data tables and you require some type
			of authorization to access the app.  In order to convert this into
			a real working application you will need to customize each page as needed.
			The philosophy behind the auto-generated code is to
			generate more code than you need.  You can and should delete the controllers,
			methods and views that you don't need.</p>

			<h4>UI Controls</h4>

			<p>The UI controls for editing fields are generated based on the database column types.
			The generator doesn't know the <i>purpose</i> of each field, though.  For example an INT
			field may be best displayed as a regular input, a slider or an on/off switch.  It's
			possible that the field shouldn't be editable by the user at all.
			The generator doesn't know these things and so it makes a best guess based on
			column types and sizes.  You will most likely have to switch out UI controls that
			are best for your application.  Bootstrap provides a lot of great UI controls
			for you to use.</p>

			<h4>Controllers</h4>

			<p>One controller has been created for each table in the application.
			The controllers are located in /libs/Controller/.
			If a particular table is not directly editable then the controller and
			view templates should be deleted.  An example might be a table
			used in a many-to-many assignment.</p>

			<h4>Models</h4>

			<p>Several Model files have been created for each table in the application.
			The model files are located in /libs/Model/.
			If your schema changes you can re-generate only the DAO (data-access object)
			files by selecting the DAO-Only package in class builder.  As long as you
			don't touch files in the /libs/Model/DAO/ folder then you can safely make
			changes to your database schema and regenerate code without losing any
			of your customizations.</p>

		</div>
		<div class="modal-footer">
			<button id="okButton" data-dismiss="modal" class="btn btn-primary">Let's Rock...</button>
		</div>
	</div>
	<div class="container">
		<div class="span3"></div>
		<div class="carouselBox span5">
			<!-- Added Carousel -->
			<div id="myCarousel" class="carousel slide">
		    <ol class="carousel-indicators">
		    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		    <li data-target="#myCarousel" data-slide-to="1"></li>
		    <li data-target="#myCarousel" data-slide-to="2"></li>
		    </ol>
		    <!-- Carousel items -->
		    <div class="carousel-inner">
		    <div class="active item">
		    	<img alt="" src="images/TheShawshankRedemption.jpg"></img>
		    </div>
		    <div class="item">
		    	<img alt="" src="images/TheReturnOfTheKing.jpg"></img>
		    </div>
		    <div class="item">
		    	<img alt="" src="images/Inception.jpg"></img>
			</div>
		    </div>
		    <!-- Carousel nav -->
		    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
		    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
		    </div>
		</div>
	</div>
	<div class="container">

		<!-- Main hero unit for a primary marketing message or call to action -->
		<div class="hero-unit">
			<h1>Movitory <i class="icon-thumbs-up"></i></h1>
			<p>This application is built by Robson Lunardelli and Lingfu Zhang. The application focus on
			managing personal movie collection. Have you became frustrated by losing many precious movies?
			Have you ruined a date by picking the wrong movies? Please use Movitory to help solve these problems!
			Register your account and be free right now! </p>
			
			<p>The application was generated with Phreeze 3.3.5 HEAD.
			Running on Phreeze <?php $this->eprint($this->PHREEZE_VERSION); ?><?php if ($this->PHREEZE_PHAR) { $this->eprint(' (' . basename($this->PHREEZE_PHAR) . ')'); } ?>.</p>
			
			<a class="btn btn-primary btn-large" data-toggle="modal" href="#getStartedDialog">Register &raquo;</a></p>
		</div>

		<!-- Example row of columns -->
		<div class="row">
			<div class="span3">
				<h2><i class="icon-film"></i> Medium</h2>
				 <p>VHS, DVD, Blu-ray, VOD... There are just so many different types of mediums. 
				 	And then there are Hulu, Netflix, Amazon Instant Video... Once you have all, 
				 	Finding movies might not be that easy.</p>
				<p><a class="btn" href="http://phreeze.com/">See Testimonies &raquo;</a></p>
			</div>
			<div class="span3">
				<h2><i class="icon-list"></i> Selection</h2>
				 <p>Set up a group for date night, and put movies in that group as you watching them.
				 	So next time when things is going well, the perfect movie just right at your fingertip.</p>
				<p><a class="btn" href="http://documentcloud.github.com/backbone/">See Testimonies &raquo;</a></p>
		 	</div>
			<div class="span3">
				<h2><i class="icon-th-large"></i> More</h2>
				<p>Libaries and movies rental companies, we are here for you. 
					The application designed with scalibilty in mind. 
					With help, we can further developing this to fit your every needs.</p>
				<p><a class="btn" href="http://twitter.github.com/bootstrap/">Contact Us &raquo;</a></p>
			</div>
			<div class="span3">
				<h2><i class="icon-heart"></i> Funding</h2>
				<p>The following company has funded the project:
					<p>You can be the first one!</p>
					<p><a class="btn" href="http://twitter.github.com/bootstrap/">Contact Us &raquo;</a></p>
				All fundings and supports are appreciated.
				</p>
			</div>
		</div>

	</div> <!-- /container -->

<?php
	$this->display('_Footer.tpl.php');
?>